# 04 Customer Analysis RFM

In [1]:
import pandas as pd

df_clean = pd.read_csv("C:\\Users\\Siddhesh\\Downloads\\Projects\\E-commerce\\ecommerce-sales-customer-intelligence\\data\\retail_clean.csv")

print(df_clean.shape)
df_clean.head()

(19469, 13)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue,Year,Month,YearMonth,IsCancelled
0,555150,22762,CUPBOARD 3 DRAWER MA CAMPAGNE,1,2011-05-31 15:53:00,29.17,NaN,United Kingdom,29.17,2011,5,2011-05,False
1,575477,22645,CERAMIC HEART FAIRY CAKE MONEY BANK,1,2011-11-09 16:14:00,3.29,NaN,United Kingdom,3.29,2011,11,2011-11,False
2,538177,84596E,SMALL LICORICE DES PINK BOWL,1,2010-12-10 09:51:00,2.51,NaN,United Kingdom,2.51,2010,12,2010-12,False
3,575930,23378,PACK OF 12 50'S CHRISTMAS TISSUES,1,2011-11-11 17:58:00,0.83,NaN,United Kingdom,0.83,2011,11,2011-11,False
4,546890,22084,PAPER CHAIN KIT EMPIRE,6,2011-03-17 18:18:00,2.95,13394.0,United Kingdom,17.70,2011,3,2011-03,False

In [4]:
df_clean['InvoiceDate'] = pd.to_datetime(df_clean['InvoiceDate'])
df_clean['InvoiceDate'].dtype

dtype('<M8[us]')

In [ ]:
import pandas as pd
import datetime as dt

# Convert InvoiceDate to datetime
df_clean['InvoiceDate'] = pd.to_datetime(df_clean['InvoiceDate'])

# Create snapshot date
snapshot_date = df_clean['InvoiceDate'].max() + dt.timedelta(days=1)

print("Snapshot Date:", snapshot_date)
print(df_clean['InvoiceDate'].dtype)

Snapshot Date: 2011-12-10 12:50:00
datetime64[us]

In [7]:
rfm = df_clean.groupby('CustomerID').agg(
    Recency=('InvoiceDate', lambda x: (snapshot_date - x.max()).days),
    Frequency=('InvoiceNo', 'nunique'),
    Monetary=('Revenue', 'sum')
).reset_index()

In [8]:
rfm.head()

   CustomerID  Recency  Frequency  Monetary
0     12347.0      130          3     55.40
1     12348.0      358          1    146.16
2     12349.0       19          1    103.38
3     12352.0       36          2     29.50
4     12354.0      232          1     37.60

In [10]:
df_clean['Revenue'] = df_clean['Quantity'] * df_clean['UnitPrice']
df_clean['Revenue'].head()

0    29.17
1     3.29
2     2.51
3     0.83
4    17.70
Name: Revenue, dtype: float64